// ---------------------------------------------------------------------------
// Spavn Engine — Codex CLI renderer
// Produces ~/.codex/agents/AGENTS.md instructions file.
// Codex agents are configured via TOML (user-specific), so we only render
// the instructions markdown file here.
// ---------------------------------------------------------------------------

import * as fs from "fs";
import * as path from "path";
import * as os from "os";
import type BetterSqlite3 from "better-sqlite3";
import type { Renderer } from "./index.js";
import type { SyncResult } from "../types.js";
import { AgentStore } from "../agents.js";
import { SkillStore } from "../skills.js";
import { TargetStore } from "../targets.js";
import { registerRenderer } from "./index.js";

// ---------------------------------------------------------------------------
// CodexRenderer
// ---------------------------------------------------------------------------

class CodexRenderer implements Renderer {
  private agents: AgentStore;
  private skills: SkillStore;
  private targets: TargetStore;

  constructor(private db: BetterSqlite3.Database) {
    this.agents = new AgentStore(db);
    this.skills = new SkillStore(db);
    this.targets = new TargetStore(db);
  }

  // ---- renderAgent ----------------------------------------------------------

  /**
   * Codex doesn't use per-agent .md files (agents are configured in TOML).
   * Returns the agent's system prompt as plain text for API consumers.
   */
  renderAgent(agentId: string): string {
    const agent = this.agents.get(agentId);
    if (!agent) throw new Error(`Agent not found: ${agentId}`);
    return agent.system_prompt;
  }

  // ---- renderInstructions ---------------------------------------------------

  renderInstructions(): string {
    const skills = this.skills.list();
    const knowledgeSkills = skills.filter((s) => s.kind === "knowledge");
    const enhancedSkills = skills.filter((s) => s.kind === "enhanced");
    const agents = this.agents.list();

    const agentList = agents
      .map((a) => `- **${a.id}**: ${a.description}`)
      .join("\n");

    return `# Spavn Agents — Project Instructions

> Auto-generated by \`npx spavn-agents install --target codex\`. Do not edit manually.

## Overview

Spavn Agents provides structured development workflows: plan \u2192 build \u2192 quality gate \u2192 ship.

## Default Workflow

When starting a new task or session, always default to the architect workflow first to plan the work before implementing. Only skip planning for trivial changes (typo fixes, single-line edits).

1. **Plan** \u2014 Analyze requirements and create an implementation plan
2. **Implement** \u2014 Execute the plan with iterative build+test verification
3. **Fix** \u2014 Quick bug fixes with minimal changes

## Available Agents

${agentList}

## Available Skills

${knowledgeSkills.map((s) => `  - ${s.id}`).join("\n")}

## Enhanced Skills (via worker agent)

${enhancedSkills.map((s) => `  - ${s.id}`).join("\n")}

## Quality Gate

After implementation, assess change scope and launch parallel tool calls:
- **Trivial** (docs only): Skip quality gate
- **Low** (tests/config): Testing worker only
- **Standard** (normal code): Testing + Security + Audit + Docs workers
- **High** (auth/payments/infra): All workers including Perf and DevOps
`;
  }

  // ---- sync -----------------------------------------------------------------

  sync(opts?: { scope?: string; projectPath?: string }): SyncResult {
    const target = this.targets.getTarget("codex");
    if (!target) throw new Error("Codex target not configured");

    const configDir = target.config_dir.replace("~", os.homedir());
    const agentsDir = path.join(configDir, "agents");

    fs.mkdirSync(agentsDir, { recursive: true });

    const result: SyncResult = {
      target: "codex",
      agentsWritten: [],
      skillsWritten: [],
      instructionsWritten: false,
      errors: [],
    };

    // Render instructions file (agents/AGENTS.md)
    if (target.instructions_file) {
      try {
        const content = this.renderInstructions();
        const filePath = path.join(configDir, target.instructions_file);
        fs.mkdirSync(path.dirname(filePath), { recursive: true });
        fs.writeFileSync(filePath, content);
        result.instructionsWritten = true;
      } catch (err) {
        result.errors.push(`Instructions: ${(err as Error).message}`);
      }
    }

    return result;
  }
}

// Self-register on import.
registerRenderer("codex", (db) => new CodexRenderer(db));

export { CodexRenderer };
