// ---------------------------------------------------------------------------
// Spavn Engine — Qwen CLI renderer
// Produces ~/.qwen/agents/*.md (YAML frontmatter + system prompt)
// and ~/.qwen/QWEN.md instructions file.
// ---------------------------------------------------------------------------

import * as fs from "fs";
import * as path from "path";
import * as os from "os";
import type BetterSqlite3 from "better-sqlite3";
import type { Renderer } from "./index.js";
import type { SyncResult } from "../types.js";
import { AgentStore } from "../agents.js";
import { SkillStore } from "../skills.js";
import { TargetStore } from "../targets.js";
import { registerRenderer } from "./index.js";

// ---------------------------------------------------------------------------
// Tool-name mapping: OpenCode name -> Qwen CLI tool name
// ---------------------------------------------------------------------------

const NATIVE_TOOL_MAP: Record<string, string> = {
  read: "read_file",
  write: "write_file",
  edit: "edit_file",
  bash: "run_shell_command",
  glob: "glob_tool",
  grep: "grep_search",
};

const NATIVE_TOOL_NAMES = new Set(Object.keys(NATIVE_TOOL_MAP));

/**
 * Map an OpenCode tool name to its Qwen CLI representation.
 *
 * - Native tools (read, write, ...) become Qwen equivalents.
 * - Everything else is a Spavn MCP tool: `mcp_spavn-agents_{name}`.
 */
function mapToolName(toolName: string): string {
  if (NATIVE_TOOL_NAMES.has(toolName)) {
    return NATIVE_TOOL_MAP[toolName];
  }
  return `mcp_spavn-agents_${toolName}`;
}

// ---------------------------------------------------------------------------
// YAML helpers — lightweight, no external dep
// ---------------------------------------------------------------------------

/** Escape a YAML string value. Wraps in quotes when necessary. */
function yamlValue(v: string): string {
  if (
    v === "" ||
    v.includes(":") ||
    v.includes("#") ||
    v.includes("{") ||
    v.includes("}") ||
    v.includes("[") ||
    v.includes("]") ||
    v.includes(",") ||
    v.includes("&") ||
    v.includes("*") ||
    v.includes("!") ||
    v.includes("|") ||
    v.includes(">") ||
    v.includes("'") ||
    v.includes('"') ||
    v.includes("%") ||
    v.includes("@") ||
    v.includes("`") ||
    v.includes("\n") ||
    v.includes("\r") ||
    v.includes("\t") ||
    v.startsWith(" ") ||
    v.endsWith(" ")
  ) {
    return JSON.stringify(v);
  }
  return v;
}

// ---------------------------------------------------------------------------
// QwenRenderer
// ---------------------------------------------------------------------------

class QwenRenderer implements Renderer {
  private agents: AgentStore;
  private skills: SkillStore;
  private targets: TargetStore;

  constructor(private db: BetterSqlite3.Database) {
    this.agents = new AgentStore(db);
    this.skills = new SkillStore(db);
    this.targets = new TargetStore(db);
  }

  // ---- renderAgent ----------------------------------------------------------

  renderAgent(agentId: string): string {
    const agent = this.agents.get(agentId);
    if (!agent) throw new Error(`Agent not found: ${agentId}`);

    const targetConfig = this.targets.getAgentTargetConfig(agentId, "qwen");
    const agentTools = this.agents.getTools(agentId);

    // ----- Determine tools list -----

    let toolsList: string[];

    if (targetConfig?.tools_override) {
      toolsList = targetConfig.tools_override;
    } else {
      toolsList = agentTools
        .filter((t) => t.allowed)
        .map((t) => mapToolName(t.tool_name));
    }

    // ----- Model -----

    const model = targetConfig?.model_override;

    // ----- Build frontmatter -----

    const lines: string[] = ["---"];
    lines.push(`name: ${yamlValue(agentId)}`);
    lines.push(`description: ${yamlValue(agent.description)}`);
    lines.push("kind: local");

    if (toolsList.length > 0) {
      lines.push("tools:");
      for (const tool of toolsList) {
        lines.push(`  - ${yamlValue(tool)}`);
      }
    }

    if (model && model !== "inherit") {
      lines.push(`model: ${yamlValue(model)}`);
    }

    lines.push(`temperature: ${agent.temperature}`);
    lines.push("max_turns: 15");
    lines.push("---");

    // ----- System prompt body -----

    return lines.join("\n") + "\n" + agent.system_prompt;
  }

  // ---- renderInstructions ---------------------------------------------------

  renderInstructions(): string {
    const skills = this.skills.list();
    const agents = this.agents.list();
    const subagents = agents.filter((a) => a.mode === "subagent");

    return `# Spavn Agents — Global Instructions

> Auto-generated by \`npx spavn-agents install --target qwen\`. Do not edit manually.

## Overview

Spavn Agents provides structured development workflows: plan → build → quality gate → ship.
All 33 tools are available via MCP server (\`npx spavn-agents mcp\`).

## Default Workflow

When starting a new task or session, always default to the architect workflow first to plan the work before implementing. Only skip planning for trivial changes (typo fixes, single-line edits).

1. **Plan** — Analyze requirements and create an implementation plan
2. **Implement** — Execute the plan with iterative build+test verification
3. **Fix** — Quick bug fixes with minimal changes

## Available Skills

${skills.map((s) => `  - ${s.id}`).join("\n")}

## Custom Agents

${subagents.map((a) => a.id).join(", ")}

## Quality Gate

After implementation, assess change scope and launch parallel tool calls:
- **Trivial** (docs only): Skip quality gate
- **Low** (tests/config): Testing agent only
- **Standard** (normal code): Testing + Security + Audit + Docs agents
- **High** (auth/payments/infra): All agents including Perf and DevOps
`;
  }

  // ---- sync -----------------------------------------------------------------

  sync(opts?: { scope?: string; projectPath?: string }): SyncResult {
    const target = this.targets.getTarget("qwen");
    if (!target) throw new Error("Qwen target not configured");

    const configDir = target.config_dir.replace("~", os.homedir());
    const agentsDir = path.join(configDir, "agents");

    fs.mkdirSync(agentsDir, { recursive: true });

    const result: SyncResult = {
      target: "qwen",
      agentsWritten: [],
      skillsWritten: [],
      instructionsWritten: false,
      errors: [],
    };

    // Render each agent
    const agents = this.agents.list();
    for (const agent of agents) {
      try {
        const content = this.renderAgent(agent.id);
        const filePath = path.join(agentsDir, `${agent.id}.md`);
        fs.writeFileSync(filePath, content);
        result.agentsWritten.push(agent.id);
      } catch (err) {
        result.errors.push(`Agent ${agent.id}: ${(err as Error).message}`);
      }
    }

    // Render instructions file
    if (target.instructions_file) {
      try {
        const content = this.renderInstructions();
        const filePath = path.join(configDir, target.instructions_file);
        fs.writeFileSync(filePath, content);
        result.instructionsWritten = true;
      } catch (err) {
        result.errors.push(`Instructions: ${(err as Error).message}`);
      }
    }

    return result;
  }
}

// Self-register on import.
registerRenderer("qwen", (db) => new QwenRenderer(db));

export { QwenRenderer };
